
[character]      # The name of the module we are configuring is "character"
success_symbol = "ğŸ˜¹ âœ"     # The "symbol" segment is being set to "âœ"
error_symbol = "ğŸ™€ âœ—"


[hostname]
ssh_only = false
style = "bold dimmed blue"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = "ğŸ“¥"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[kubernetes]
#format = '[â›µ ($user on )($cluster in )$context \($namespace\)](bright green) '
format = '[â›µ ($user)/($cluster)\($namespace\)](bright green) '
disabled = false
# [kubernetes.context_aliases]
# 'dev.local.cluster.k8s' = 'dev'
# '.*/openshift-cluster/.*' = 'openshift'
# 'gke_.*_(?P<var_cluster>[\w-]+)' = 'gke-$var_cluster'
# [kubernetes.user_aliases]
# 'dev.local.cluster.k8s' = 'dev'
# 'root/.*' = 'root'
